#!/bin/bash
set -e

echo "[Mulang::Docs] Checking mkdocs is installed"
command -v mkdocs >/dev/null 2>&1 || {
  echo >&2 "[Mulang::Docs] mkdocs not found. Please install it first.  Aborting..."; exit 1;
}

echo "[Mulang::Docs] Checking wget is installed"
command -v wget >/dev/null 2>&1 || {
  echo >&2 "[Mulang::Docs] wget not found. Please install it first.  Aborting..."; exit 1;
}

echo "[Mulang::Docs] Checking unzip is installed"
command -v unzip >/dev/null 2>&1 || {
  echo >&2 "[Mulang::Docs] unzip not found. Please install it first.  Aborting..."; exit 1;
}

DOCSDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

echo "[Mulang::Docs] Cleaning up resources..."
rm -f ${DOCSDIR}/js/mulang.js
rm -f ${DOCSDIR}/js/mumuk-styles.js
rm -f ${DOCSDIR}/css/mumuki-styles.js

echo "[Mulang::Docs] Installing mulang.js..."
TMPFILE=mulang.js.zip
wget https://github.com/mumuki/mulang/releases/download/v4.2.0/mulang.js.zip -O ${TMPFILE}
unzip -d ${DOCSDIR}/js ${TMPFILE}
rm ${TMPFILE}

echo "[Mulang::Docs] Installing mumuki-styles..."
wget https://raw.githubusercontent.com/mumuki/mumuki-styles/master/dist/css/mumuki-styles.css -O ${DOCSDIR}/css/mumuki-styles.css
wget https://raw.githubusercontent.com/mumuki/mumuki-styles/master/dist/javascripts/mumuki-styles.js -O ${DOCSDIR}/js/mumuki-styles.js

echo "[Mulang::Docs] Building the docs for first time..."
mkdocs build

echo "[Mulang::Docs] Done! Now run mkdocs serve"
