resolver: lts-23.28
allow-newer: true
packages:
  - "."
extra-deps:
  - inflections-0.2.0.1
  - github: mumuki/language-javascript
    commit: 7cadfa30838c69d165df39a5c1524dae5a0fc81f
  - github: bjpop/language-python
    commit: 9fa3c8b258c05d388a0cbb4e69c639bd9fddfdbb
    subdirs:
      - language-python
flags: {}
extra-package-dbs: []
